version: "3.8"
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: ${APP_NAME:?jenkins}-app
    restart: unless-stopped
    privileged: true
    user: root
    ports:
      - ${PORT:?8080:8080}
      - 50000:50000
    volumes:
      - jenkins-data:/var/jenkins_home

volumes:
  jenkins-data:
    name: ${APP_NAME:?jenkins}-data
    external: true